# Generated by Django 4.0.6 on 2022-07-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeId', models.CharField(max_length=200, null=True)),
                ('EmployeeName', models.CharField(max_length=50, null=True)),
                ('Designation', models.CharField(max_length=50, null=True)),
                ('JoinedDate', models.DateField()),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('EMail', models.CharField(max_length=50, null=True)),
                ('Salary', models.IntegerField(default=0)),
                ('WorkingDays', models.IntegerField(default=0)),
            ],
        ),
    ]
