# Generated by Django 4.0.6 on 2022-08-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='EMail',
            new_name='Email',
        ),
    ]
